name: 'Alpha Release'

on:
  schedule:
    - cron: '10/10 * * * *' # weekly (Monday) 12PM PST
  push:
    branches:
      - master

jobs:
  test:
    name: Test latest code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies for master
        run: yarn install --frozen-lockfile --non-interactive
      - name: Basic Tests
        env:
          CI: true
          ASSERT_ALL_DEPRECATIONS: true
        run: yarn test

  release:
    name: Run publish script
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies for master
        run: yarn install --frozen-lockfile --non-interactive
      - name: Get next alpha version
        run: NEXT_VERSION=$(node bin/determine-next-alpha-version.js)
      - name: Make sure git user is setup
        run: |
          git config --local user.email 'cron@example.com'
          git config --local user.name 'Ember Data Cron CI'
      - name: publish with script
        run: node bin/publish.js canary --useVersion=$NEXT_VERSION
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: push branch + tag
        run: git push origin HEAD --follow-tags
